- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: remove temporary folder
      file:
        path: tmp
        state: absent
    - name: create temporary folders (empty)
      file:
        path: "{{ item }}"
        state: directory
      loop: [tmp, tmp/tls, tmp/authentication-config, tmp/encryption-config, tmp/ssh]




