- hosts: bootstrap
  remote_user: ubuntu
  become: true
  vars_files:
    - vars/variables.yaml
  tasks:
  - name: get kubectl
    get_url:
      url: "{{ kubectl_URL }}"
      dest: /usr/local/bin/kubectl
      mode: 0755
  - name: output kubectl version
    command: kubectl version --client
