- hosts: 127.0.0.1
  connection: local
  tasks:
    # generating SSH keypair for web console access
    - name: generate OpenSSH keypair
      shell: 'yes "y" | ssh-keygen -t rsa -b 4096 -N "" -C "webconsole keypair" -f tmp/ssh/webconsole_keypair'

# distribute keypair bits
- hosts: bootstrap
  remote_user: ubuntu
  become: true
  tasks:
    - name: upload private key
      synchronize:
        src: tmp/ssh/webconsole_keypair
        dest: /home/ubuntu/.ssh

    - name: change file permissions of private key file
      file:
        path: /home/ubuntu/.ssh/webconsole_keypair
        owner: ubuntu
        group: ubuntu
        mode: 0600

# append pub key to all ubuntu users on all nodes
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: append public key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', 'tmp/ssh/webconsole_keypair.pub') }}"
